package org.idempiere.cli.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Represents code generated by AI, structured as a set of files
 * plus optional metadata changes (MANIFEST.MF additions, etc.).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GeneratedCode {

    @JsonProperty("files")
    private List<GeneratedFile> files;

    @JsonProperty("manifest_additions")
    private List<String> manifestAdditions;

    @JsonProperty("build_properties_additions")
    private List<String> buildPropertiesAdditions;

    public GeneratedCode() {}

    public List<GeneratedFile> getFiles() {
        return files != null ? files : List.of();
    }

    public void setFiles(List<GeneratedFile> files) {
        this.files = files;
    }

    public List<String> getManifestAdditions() {
        return manifestAdditions != null ? manifestAdditions : List.of();
    }

    public void setManifestAdditions(List<String> manifestAdditions) {
        this.manifestAdditions = manifestAdditions;
    }

    public List<String> getBuildPropertiesAdditions() {
        return buildPropertiesAdditions != null ? buildPropertiesAdditions : List.of();
    }

    public void setBuildPropertiesAdditions(List<String> buildPropertiesAdditions) {
        this.buildPropertiesAdditions = buildPropertiesAdditions;
    }

    /**
     * Writes all generated files to the plugin directory.
     * Does NOT overwrite existing files.
     *
     * @param pluginDir the plugin root directory
     * @throws IOException if writing fails
     */
    public void writeTo(Path pluginDir) throws IOException {
        for (GeneratedFile file : getFiles()) {
            Path target = pluginDir.resolve(file.getPath());

            // Security: reject path traversal
            if (!target.normalize().startsWith(pluginDir.normalize())) {
                System.err.println("  Skipped (path traversal): " + file.getPath());
                continue;
            }

            if (Files.exists(target)) {
                System.err.println("  Skipped (already exists): " + target);
                continue;
            }

            Files.createDirectories(target.getParent());
            Files.writeString(target, file.getContent());
            System.out.println("  Created: " + target);
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class GeneratedFile {

        @JsonProperty("path")
        private String path;

        @JsonProperty("content")
        private String content;

        public GeneratedFile() {}

        public GeneratedFile(String path, String content) {
            this.path = path;
            this.content = content;
        }

        public String getPath() {
            return path;
        }

        public void setPath(String path) {
            this.path = path;
        }

        public String getContent() {
            return content;
        }

        public void setContent(String content) {
            this.content = content;
        }
    }
}
