package org.idempiere.cli.plugins.experimental.add;

import io.quarkus.arc.properties.IfBuildProperty;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.idempiere.cli.model.ProjectContext;
import org.idempiere.cli.plugin.add.AddGenerationPlugin;
import org.idempiere.cli.plugins.experimental.ai.SmartScaffoldService;

import java.nio.file.Path;
import java.util.Map;
import java.util.Optional;

/**
 * Experimental AI-assisted generation plugin.
 * Enabled only when idempiere.experimental.ai.enabled=true.
 */
@ApplicationScoped
@IfBuildProperty(name = "idempiere.experimental.ai.enabled", stringValue = "true")
public class AiExperimentalAddGenerationPlugin implements AddGenerationPlugin {

    @Inject
    SmartScaffoldService smartScaffoldService;

    @Override
    public String id() {
        return "experimental-ai";
    }

    @Override
    public int order() {
        return 10;
    }

    @Override
    public Optional<AddGenerationResult> tryGenerate(String type,
                                                     String name,
                                                     Path pluginDir,
                                                     String pluginId,
                                                     ProjectContext projectContext,
                                                     Map<String, Object> extraData) {
        return smartScaffoldService.generate(type, name, pluginDir, pluginId, extraData)
                .map(code -> AddGenerationResult.generated(code, "generated by experimental-ai"));
    }
}
