package org.idempiere.cli.service.check;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PomXmlCheckTest {

    private final PomXmlCheck check = new PomXmlCheck();

    @Test
    void acceptsTychoEclipsePluginPackaging(@TempDir Path dir) throws IOException {
        // Multi-module submodule generated by 'idempiere-cli init' — tycho-maven-plugin
        // is declared in the parent pom, not here.
        Files.writeString(dir.resolve("pom.xml"),
                "<project>\n" +
                "  <packaging>eclipse-plugin</packaging>\n" +
                "</project>\n");

        CheckResult result = check.check(dir);

        assertEquals(CheckResult.Status.OK, result.status());
        assertTrue(result.message().contains("eclipse-plugin"));
    }

    @Test
    void acceptsLegacyBundlePackaging(@TempDir Path dir) throws IOException {
        Files.writeString(dir.resolve("pom.xml"),
                "<project>\n" +
                "  <packaging>bundle</packaging>\n" +
                "</project>\n");

        CheckResult result = check.check(dir);

        assertEquals(CheckResult.Status.OK, result.status());
        assertTrue(result.message().contains("bundle"));
    }

    @Test
    void rejectsPlainPomPackaging(@TempDir Path dir) throws IOException {
        Files.writeString(dir.resolve("pom.xml"),
                "<project>\n" +
                "  <packaging>pom</packaging>\n" +
                "</project>\n");

        CheckResult result = check.check(dir);

        assertEquals(CheckResult.Status.FAIL, result.status());
        assertTrue(result.message().contains("eclipse-plugin"));
        assertTrue(result.message().contains("bundle"));
    }

    @Test
    void rejectsMissingPackagingElement(@TempDir Path dir) throws IOException {
        Files.writeString(dir.resolve("pom.xml"),
                "<project>\n" +
                "  <artifactId>foo</artifactId>\n" +
                "</project>\n");

        CheckResult result = check.check(dir);

        assertEquals(CheckResult.Status.FAIL, result.status());
    }

    @Test
    void failsWhenPomMissing(@TempDir Path dir) {
        CheckResult result = check.check(dir);

        assertEquals(CheckResult.Status.FAIL, result.status());
        assertEquals("Not found", result.message());
    }
}
